# Generated by Django 6.1.1 on 2026-10-07 07:59

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.CharField(blank=True, help_text='One line shown on category tiles and at the top of the list page.', max_length=160)),
                ('menu_blurb', models.CharField(blank=True, help_text='Shorter line for the mega menu. Falls back to the blurb.', max_length=120)),
                ('icon', models.CharField(default='a-tube', help_text='Illustration id from templates/partials/sprite.html, for example a-tube.', max_length=40)),
                ('colors', models.CharField(default='#BA3521,#8A98A3,#CDBF9B', help_text='Up to three hex colors, comma separated.', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=store.models.new_order_number, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Payment failed'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=40, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('amount', models.PositiveIntegerField(help_text='In paise.')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=10)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('brand', models.CharField(help_text='Brand, or the maker for handmade pieces.', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price. Shown struck through next to the sale price.', max_digits=10, null=True)),
                ('badge', models.CharField(blank=True, help_text='For example New, Sale or Bestseller.', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='a-tube', help_text='Illustration id from templates/partials/sprite.html.', max_length=40)),
                ('colors', models.CharField(default='#BA3521,#8A98A3,#CDBF9B', help_text='Up to three hex colors, comma separated.', max_length=60)),
                ('home_tab', models.CharField(blank=True, choices=[('', 'Not on the homepage'), ('best', 'Bestsellers'), ('new', 'New arrivals'), ('hand', 'Handmade picks')], default='', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first in Featured order.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Custom framing choices, empty for catalog products.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', validators=[store.models.validate_image_size])),
                ('alt', models.CharField(blank=True, help_text='Short description for screen readers.', max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers first. The first image is the main one.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
