# Generated by Django 6.1.1 on 2026-10-07 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('blurb', models.CharField(blank=True, help_text='One line shown on category tiles and at the top of the list page.', max_length=160)),
                ('menu_blurb', models.CharField(blank=True, help_text='Shorter line for the mega menu. Falls back to the blurb.', max_length=120)),
                ('icon', models.CharField(default='a-tube', help_text='Illustration id from templates/partials/sprite.html, for example a-tube.', max_length=40)),
                ('colors', models.CharField(default='#BA3521,#8A98A3,#CDBF9B', help_text='Up to three hex colors, comma separated.', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('brand', models.CharField(help_text='Brand, or the maker for handmade pieces.', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price. Shown struck through next to the sale price.', max_digits=10, null=True)),
                ('badge', models.CharField(blank=True, help_text='For example New, Sale or Bestseller.', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='a-tube', help_text='Illustration id from templates/partials/sprite.html.', max_length=40)),
                ('colors', models.CharField(default='#BA3521,#8A98A3,#CDBF9B', help_text='Up to three hex colors, comma separated.', max_length=60)),
                ('home_tab', models.CharField(blank=True, choices=[('', 'Not on the homepage'), ('best', 'Bestsellers'), ('new', 'New arrivals'), ('hand', 'Handmade picks')], default='', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first in Featured order.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
